apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: selfheal-api-default-deny-egress
  namespace: selfheal
spec:
  podSelector:
    matchLabels:
      app: selfheal-api
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 3200
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318
        - protocol: TCP
          port: 443
